# Generated by Django 5.1.6 on 2025-02-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='converted_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='converted_grade_card',
            field=models.TextField(blank=True, null=True),
        ),
    ]
